name: Node CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: npm install
        run: npm install

      - name: yarn run lint
        run: yarn run lint
